import type { Metadata } from "next";
import { Agdasima } from "next/font/google";
import "./globals.css";

export const Agdas_font = Agdasima({
  subsets: ['latin'],
  weight: "400"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Agdas_font.className} antialiased p-2 md:p-4`}
      >
        {children}
      </body>
    </html>
  );
}
