import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";

export const Manrope_Font = Manrope({
  subsets: ['latin'],
  weight: '400'
})

export const metadata: Metadata = {
  title: "Baxter: Your Stock Search Tool",
  description: "Generated by Create Next App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Manrope_Font.className} antialiased p-1 md:p-2 my-1 md:my-2`}
      >
        {children}
      </body>
    </html>
  );
}
